# By default, SwiftLint uses a set of sensible default rules you can adjust:

# rule identifiers turned on by default to exclude from running
opt_in_rules:
- force_unwrapping
-  implicitly_unwrapped_optional

function_body_length:
  warning: 50 # default 40
  error: 50

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Vape-X/AppDelegate.swift
  - Vape-X/SceneDelegate.swift
#implicitly_unwrapped_optional:
#  severity: warning
force_unwrapping:
  severity: error
type_name:
  allowed_symbols: "_"
