default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
    

  end

  desc "Runs all the tests"
  lane :test do
    scan(include_simulator_logs: false) 
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
     
  end
  ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
  ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
end
